parameters:
  name: agentName

stages:
- stage:
  displayName: 'alpha NOT selected message'
  pool:
    name: ${{ parameters.agentName }}
    vmImage: 'ubuntu-latest'
  jobs:
  - job:
    displayName: 'print NOT message'
    steps:
    - bash: |
          which bash
          echo Hello $name
      displayName: 'bash NOT alpha'
