name: 1.0$(rev:.r)

trigger:
  branches:
    exclude:
     - master
     - feature/*
     - develop/*
     - task/*
     - hotfix/*

parameters:
  - name: agentName
    displayName: 'Agent Pool'
    type: string
    default: 'Azure Pipelines'
    values:
      - 'Azure Pipelines'
      - 'Linux Agents'
      - 'MS Windows Agents'

  - name: artefactSource
    displayName: 'Source'
    default: 'Latest from Master'
    values:
      - 'Latest'
      - 'Latest from Master'
      - 'Specific'
  
  - name: artefactBuildId
    displayName: 'Build Id'
    default: 000

  - name: alpha
    displayName: 'Alpha'
    type: boolean
    default: false

  - name: beta
    displayName: 'Beta'
    type: boolean
    default: false

  - name: gamma
    displayName: 'Gamma'
    type: boolean
    default: false

# variables:
  # - group: 'sample variable group'
  # - name: sample_variable
  #   value: 'sample variable value'

stages:
  - ${{ if eq(parameters.alpha, true) }}:
    - template: alpha-selected.yml
      parameters:
        agentName: ${{ parameters.agentName }}

  - ${{ if eq(parameters.alpha, false) }}:
    - template: alpha-not-selected.yml
      parameters:
          agentName: ${{ parameters.agentName }}

  - ${{ if eq(parameters.beta, true) }}:
    - template: beta-selected.yml

  - ${{ if eq(parameters.beta, false) }}:
    - template: beta-not-selected.yml

  - ${{ if eq(parameters.gamma, true) }}:
    - template: gamma-selected.yml

  - ${{ if eq(parameters.gamma, false) }}:
    - template: gamma-not-selected.yml